In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
base_census = pd.read_csv('Bases de dados\census.csv')
base_census.info()

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\diego\AppData\Local\Temp\ipykernel_16280\3322210433.py:1: SyntaxWarning: invalid escape sequence '\c'
  base_census = pd.read_csv('Bases de dados\census.csv')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   final-weight    32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loos    32561 non-null  int64 
 12  hour-per-week   32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [3]:
X_census = base_census.iloc[:, 0:14].values
y_census = base_census.iloc[:, 14]

In [4]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()


In [5]:
X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [6]:
X_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
X_census = scaler_census.fit_transform(X_census)

In [8]:
from sklearn.model_selection import train_test_split
X_census_treinamento, X_census_teste, y_census_treinamento, y_census_teste = train_test_split(X_census, y_census, test_size=0.15, random_state=0)

In [9]:
X_census_treinamento.shape, X_census_teste.shape

((27676, 14), (4885, 14))

#### PCA (Principal copmponet analisys)

In [10]:
from sklearn.decomposition import PCA

In [15]:
pca = PCA(n_components=8)


In [27]:
X_census_treinamento_pca = pca.fit_transform(X_census_treinamento)
X_census_testes_pca = pca.transform(X_census_teste)


In [28]:
X_census_treinamento_pca.shape, X_census_testes_pca.shape

((27676, 8), (4885, 8))

In [29]:
pca.explained_variance_ratio_

array([0.151561  , 0.10109701, 0.08980379, 0.08076277, 0.07627678,
       0.07357646, 0.06772289, 0.06690789])

In [30]:
pca.explained_variance_ratio_.sum()

0.7077085943199317

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
random_forest_census_pca = RandomForestClassifier(n_estimators=40, random_state=0, criterion = 'entropy')
random_forest_census_pca.fit(X_census_treinamento_pca, y_census_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [34]:
previsoes = random_forest_census_pca.predict(X_census_testes_pca)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [35]:
y_census_teste

22278     <=50K
8950      <=50K
7838      <=50K
16505     <=50K
19140      >50K
          ...  
28592     <=50K
17008     <=50K
25123     <=50K
21036     <=50K
13998     <=50K
Name: income, Length: 4885, dtype: object

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.8343909928352098

### # Kernel pCA

In [37]:
from sklearn.decomposition import KernelPCA

In [38]:
kpca = KernelPCA(n_components=8, kernel='rbf')
X_census_treinamento_kpca = kpca.fit_transform(X_census_treinamento)
X_census_teste_kpca = kpca.transform(X_census_teste)

In [39]:
X_census_treinamento_kpca.shape, X_census_teste_kpca.shape

((27676, 8), (4885, 8))

In [40]:
X_census_treinamento_kpca

array([[ 0.18894283,  0.05517031, -0.08653531, ...,  0.41350358,
         0.06383854, -0.25147161],
       [ 0.16165577, -0.07855932, -0.03858728, ..., -0.01994034,
        -0.00338877, -0.29452204],
       [-0.085163  , -0.27486159,  0.12920466, ...,  0.19029531,
         0.04692292,  0.13187157],
       ...,
       [-0.27872683,  0.40033469,  0.20104327, ..., -0.17392304,
        -0.16108872,  0.00683154],
       [ 0.21829898, -0.12392098, -0.02312817, ..., -0.12231089,
         0.33364887,  0.25177643],
       [ 0.24961467,  0.42418174,  0.12141394, ..., -0.00408799,
        -0.18258341, -0.08239723]])

In [41]:
X_census_teste_kpca

array([[-0.2305274 ,  0.09216682, -0.35889558, ...,  0.20619442,
         0.00660931, -0.14629412],
       [-0.08104678,  0.37831476,  0.25676557, ..., -0.02519549,
         0.29796703,  0.06589198],
       [ 0.29936848,  0.08812443,  0.37047773, ...,  0.18397454,
         0.25229655,  0.08281366],
       ...,
       [-0.34675858,  0.37151029,  0.17696698, ...,  0.04998738,
        -0.18621013,  0.11651228],
       [ 0.22278612,  0.31570043, -0.03235012, ..., -0.38373265,
         0.21927676, -0.00324746],
       [ 0.4670664 ,  0.02217354, -0.12841031, ..., -0.04612234,
         0.30518034,  0.06757151]])

In [43]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census_kpca = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
random_forest_census_kpca.fit(X_census_treinamento_kpca, y_census_treinamento)


RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [44]:
previsoes = random_forest_census_kpca.predict(X_census_teste_kpca)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [45]:
y_census_teste

22278     <=50K
8950      <=50K
7838      <=50K
16505     <=50K
19140      >50K
          ...  
28592     <=50K
17008     <=50K
25123     <=50K
21036     <=50K
13998     <=50K
Name: income, Length: 4885, dtype: object

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.8235414534288639

##### LDA

In [55]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 1)

In [56]:
X_census_treinamento_lda = lda.fit_transform(X_census_treinamento, y_census_treinamento)
X_census_teste_lda = lda.transform(X_census_teste)

In [57]:
X_census_treinamento_lda.shape, X_census_teste_lda.shape

((27676, 1), (4885, 1))

In [58]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census_lda = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
random_forest_census_lda.fit(X_census_treinamento_lda, y_census_treinamento)
previsoes = random_forest_census_lda.predict(X_census_teste_lda)

In [59]:
previsoes

array([' <=50K', ' >50K', ' <=50K', ..., ' >50K', ' >50K', ' >50K'],
      dtype=object)

In [60]:
y_census_teste

22278     <=50K
8950      <=50K
7838      <=50K
16505     <=50K
19140      >50K
          ...  
28592     <=50K
17008     <=50K
25123     <=50K
21036     <=50K
13998     <=50K
Name: income, Length: 4885, dtype: object

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.7334698055271238